name: CI

on:
  workflow_dispatch:

jobs:
  sign:
    runs-on: macos-latest
    env:
      SECRET_URL: "${{ secrets.URL }}"
      SECRET_KEY: "${{ secrets.KEY }}"
    steps:
      - name: Sign
        run: |
          ./sign.sh
