name: CI

on:
  workflow_dispatch:
    inputs:
      download_suffix:
        description: "Download suffix"
        required: true
      upload_suffix:
        description: "Upload suffix"
        required: true
      cert_suffix:
        description: "Certificate suffix"
        required: true
      prov_suffix:
        description: "Provisioning profile suffix"
        required: true
      pass_suffix:
        description: "Certificate password suffix"
        required: true

jobs:
  sign:
    runs-on: macos-latest
    env:
      DOWNLOAD_SUFFIX: "${{ github.event.inputs.download_suffix }}"
      UPLOAD_SUFFIX: "${{ github.event.inputs.upload_suffix }}"
      CERT_SUFFIX: "${{ github.event.inputs.cert_suffix }}"
      PROV_SUFFIX: "${{ github.event.inputs.prov_suffix }}"
      PASS_SUFFIX: "${{ github.event.inputs.pass_suffix }}"
      SECRET_URL: "${{ secrets.URL }}"
      SECRET_KEY: "${{ secrets.KEY }}"
    steps:
      - name: Sign
        run: |
          set -e

          echo "Obtaining files..."
          curl -s -L -H "Authorization: Bearer $SECRET_KEY" "$SECRET_URL/$CERT_SUFFIX" --output cert.p12
          curl -s -L -H "Authorization: Bearer $SECRET_KEY" "$SECRET_URL/$PROV_SUFFIX" --output prov.mobileprovision
          curl -s -L -H "Authorization: Bearer $SECRET_KEY" "$SECRET_URL/$DOWNLOAD_SUFFIX" --output file.ipa
          CERT_PASS=$(curl -s -L -H "Authorization: Bearer $SECRET_KEY" "$SECRET_URL/$PASS_SUFFIX")
          curl -s -L "https://raw.githubusercontent.com/SignTools/XReSign/master/XReSign/Scripts/xresign.sh" --output xresign.sh
          chmod +x xresign.sh

          echo "Creating keychain..."
          security create-keychain -p "1234" "sign"
          security unlock-keychain -p "1234" "sign"
          security default-keychain -s "sign"

          echo "Importing certificate..."
          security import "cert.p12" -P "$CERT_PASS" -A
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "1234" > /dev/null 2>&1
          IDENTITY=$(security find-identity -p appleID -v |  grep -o '".*"' | cut -d '"' -f 2)

          echo "Signing..."
          ./xresign.sh -s file.ipa -c "$IDENTITY" -p "prov.mobileprovision" > /dev/null 2>&1
          rm file.ipa
          mv *.ipa file.ipa

          echo "Uploading..."
          curl -s -H "Authorization: Bearer $SECRET_KEY" -F "file=@file.ipa" "$SECRET_URL/$UPLOAD_SUFFIX"
